'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gapSize=5,5#desktopScale=1#adhesiveForce=12#allForms=MainForm,False,265,40,430,40"& _ 
            "6,|PresetsTool,False,45,115,215,331,|GapSizeTool,False,700,115,215,196,|ForceToo"& _ 
            "l,False,700,316,215,130,|Test Window 1,False,45,451,650,139,TestForm|Test Window"& _ 
            " 2,False,700,451,215,139,TestForm|Test Window 3,True,-260,291,300,299,TestForm|T"& _ 
            "est Window 4,True,-365,80,300,299,TestForm#Preset=Welcome World|MainForm,False,8"& _ 
            "05,135,430,406,|PresetsTool,False,585,210,215,331,|GapSizeTool,False,1240,210,21"& _ 
            "5,196,|ForceTool,False,1240,411,215,130,|Test Window 1,False,585,546,650,139,Tes"& _ 
            "tForm|Test Window 2,False,1240,546,215,139,TestForm|Test Window 3,True,280,386,3"& _ 
            "00,299,TestForm|Test Window 4,True,175,175,300,299,TestForm#Preset=Tools Only|Ma"& _ 
            "inForm,False,1192,105,338,569,|PresetsTool,False,1535,306,215,233,|GapSizeTool,F"& _ 
            "alse,1535,105,215,196,|ForceTool,False,1535,544,215,130,|Test Window 1,True,1069"& _ 
            ",525,430,139,TestForm|Test Window 2,True,1535,311,215,353,TestForm|Test Window 3"& _ 
            ",True,544,394,300,299,TestForm|Test Window 4,True,439,183,300,299,TestForm#Prese"& _ 
            "t=Full Bottom Contact|MainForm,False,751,509,430,406,|PresetsTool,False,531,584,"& _ 
            "215,331,|GapSizeTool,False,1186,584,215,196,|ForceTool,False,1186,785,215,130,|T"& _ 
            "est Window 1,False,531,920,650,139,TestForm|Test Window 2,False,1186,920,215,139"& _ 
            ",TestForm|Test Window 3,False,1406,785,261,274,TestForm|Test Window 4,False,277,"& _ 
            "785,249,274,TestForm")>  _
        Public Property Adhesive() As String
            Get
                Return CType(Me("Adhesive"),String)
            End Get
            Set
                Me("Adhesive") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AdhesiveTest.My.MySettings
            Get
                Return Global.AdhesiveTest.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
